<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>BritanniaRenaissance.Content</AssemblyName>
    <RootNamespace>BritanniaRenaissance.Content</RootNamespace>
    <ModernUOPath Condition="'$(ModernUOPath)' == ''">$(MSBuildThisFileDirectory)..\..\..\ModernUO</ModernUOPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Server">
      <HintPath>$(ModernUOPath)\Distribution\Server.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Logger">
      <HintPath>$(ModernUOPath)\Distribution\Assemblies\Logger.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UOContent">
      <HintPath>$(ModernUOPath)\Distribution\Assemblies\UOContent.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="ModernUO.CodeGeneratedEvents.Annotations">
      <HintPath>$(ModernUOPath)\Distribution\Assemblies\ModernUO.CodeGeneratedEvents.Annotations.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <Target Name="DeployShardContentAssembly" AfterTargets="Build">
    <Copy SourceFiles="$(TargetPath)"
          DestinationFolder="$(ModernUOPath)\Distribution\Assemblies\" />
  </Target>
</Project>
